[config]
schemaVersion = "0.0.1"


[package]
namespace = "NikkelM"
name = "Vow_of_Paused_Time"
versionNumber = "1.1.0"
description = "Pauses the Vow of Time's timer outside of combat. Also allows pausing all in-game timers and tweaking the Vow's time limits for more or less of a challenge."
websiteUrl = "https://github.com/NikkelM/Hades-II-VowOfPausedTime"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.60"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods" ]
